### ISSUE TITLE
awk: illegal statement at source line 1

### ISSUE THREAD

**Issue by joy369** [daormar/thot#3]
Hi, I'm new here and I have some problem about training.

I follow the manual to train a translator of the toy_corpus provided by this project.
However, when I execute those commands : 

src_train_corpus=${PREFIX}/share/thot/toy_corpus/sp_tok_lc.train
trg_train_corpus=${PREFIX}/share/thot/toy_corpus/en_tok_lc.train
thot_tm_train -s ${src_train_corpus} -t ${trg_train_corpus} -o tm_outdir

I get many but the same error :

awk: syntax error at source line 1
 context is
	{print >>>  substr($1,length($1)-3)== <<<
awk: illegal statement at source line 1
awk: illegal statement at source line 1
/usr/local/bin//thot_pbs_gen_batch_sw_model: line 346: [: -eq: unary operator expected

I ignore those errors and keep going on executing the commands in the manual.
In the end I still can get a set of output, but I can't tell it is correct or not.
Is there any thing I do wrong? Any respond is appreciated.

**Comment by atomberg** [comment]
Hi joy369,

This warning message happens because of an error on line 309 of `utils/sw_models/thot_pbs_gen_batch_sw_model.sh` script. It can be removed by fixing this file as follows:
```
309: -  log_ext=`echo $file | $AWK '{print substr($1,length($1)-3)==".log"}'`
309: +  log_ext=`echo $file | $AWK '{print (substr($1,length($1)-3)==".log")}'` 
```
You should replace the version without the parentheses (top line) with the one with the parentheses around substr (bottom line). Rerunning `make` should copy this file to `/usr/local/bin/thot_pbs_gen_batch_sw_model` and the warning messages should disappear.

Let me know if it worked for you,
Cheers.

**Comment by daormar** [comment]
Hi,
first of all, thanks very much to atomberg for pointing out to the exact cause of the problem and proposing a solution. I think it is a portability issue related to awk, since I have never found the errors reported by joy369 when using the tool across different platforms.

I have added a patch to solve the problem permanently. It is necessary to execute `git pull` and reinstall the package. It would be great if you can confirm that now everything works correctly.

Regards.
